apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-jobs-api
labels:
  template: workbc-jobs-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
    labels:
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: wbc-app
      app.openshift.io/runtime: nodejs
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${TAG}
          name: workbc-jobs-api
          ports:
          - containerPort: 8081
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - workbc-jobs-api
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: workbc-jobs-api
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ''
- description: Tag used for the image tags
  displayName: tag
  name: TAG
  required: true
  value: latest
- description: The namespace of the OS project containing the imagestreams
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  required: true
  value: myproject-tools